import '../models/train.dart';

final List<Train> sampleTrains = [
  Train(
    id: "1",
    name: "Kovai Express",
    number: "12675",
    from: "Chennai",
    to: "Coimbatore",
    departure: "06:10",
    arrival: "14:05",
    duration: "7h 55m",
    rating: 4.6,
    trainType: 'Superfast',
    pantryAvailable: true,
    classes: [
      {'name': 'CC', 'price': '₹850', 'availability': 'CURR_AVBL 50', 'tatkal': false},
      {'name': '2S', 'price': '₹235', 'availability': 'WL 120', 'tatkal': true},
    ],
  ),
  Train(
    id: "2",
    name: "Tejas Express",
    number: "22671",
    from: "Chennai",
    to: "Madurai",
    departure: "06:00",
    arrival: "12:15",
    duration: "6h 15m",
    rating: 4.8,
    trainType: 'Tejas',
    pantryAvailable: true,
    classes: [
      {'name': 'EC', 'price': '₹1500', 'availability': 'CURR_AVBL 10', 'tatkal': false},
      {'name': 'CC', 'price': '₹1100', 'availability': 'WL 30', 'tatkal': false},
    ],
  ),
    Train(
    id: "7",
    name: "West Coast Express",
    number: "22637",
    from: "Chennai",
    to: "Mangalore",
    departure: "13:15",
    arrival: "06:40",
    duration: "17h 25m",
    rating: 4.3,
    trainType: 'Express',
    pantryAvailable: true,
    classes: [
      {'name': '2A', 'price': '₹2500', 'availability': 'CURR_AVBL 25', 'tatkal': false},
      {'name': '3A', 'price': '₹1800', 'availability': 'WL 50', 'tatkal': true},
      {'name': 'SL', 'price': '₹700', 'availability': 'CURR_AVBL 150', 'tatkal': true},
    ],
  ),
  Train(
    id: "31",
    name: "Mahal Express",
    number: "16611",
    from: "Chennai",
    to: "Mangalore",
    departure: "22:30",
    arrival: "11:45",
    duration: "13h 15m",
    rating: 4.4,
    trainType: 'Express',
    pantryAvailable: false,
    classes: [
        {'name': '3A', 'price': '₹1750', 'availability': 'RAC 20', 'tatkal': false},
        {'name': 'SL', 'price': '₹650', 'availability': 'WL 80', 'tatkal': true},
    ],
  ),
  Train(
    id: "4",
    name: "Pandian Express",
    number: "12638",
    from: "Madurai",
    to: "Chennai",
    departure: "21:20",
    arrival: "05:40",
    duration: "8h 20m",
    rating: 4.7,
  ),
  Train(
    id: "15",
    name: "Bangalore Mail",
    number: "12657",
    from: "Chennai",
    to: "Bangalore",
    departure: "23:15",
    arrival: "05:00",
    duration: "5h 45m",
    rating: 4.7,
  ),
];
